M48
; DRILL file {KiCad (6.0.2)} date Mon May 23 22:39:12 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-23T22:39:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0400
%
G90
G05
T1
X4.45Y-3.85
X4.45Y-3.95
X4.55Y-3.85
X4.55Y-3.95
T2
X4.25Y-3.05
X4.25Y-4.15
X5.25Y-3.05
X5.25Y-4.15
T0
M30
